### ISSUE TITLE
加範本

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-examples#58]
原本的白表沒有內容，我們這些喜歡音韻學而又不懂編碼的人無從入手，只能抄考其他方案的語法，請加入有多點內容的範本。

**Comment by graphemecluster** [comment]
我有計劃弄一個用 [Blockly](https://developers.google.com/blockly) 的編輯器方便不懂寫程式的用户，但團隊成員都很忙，我想短期內還是推出不了了。

**Comment by ayaka14732** [comment]
我建議還是由學習編碼開始

**Comment by 307587** [comment]
@graphemecluster 也不用那麼複雜吧？我期望的就只是「音變規則」與「編碼語法」的例子而已，如：
「並母平聲讀p，其他（即是仄聲）讀b」寫成`['並母', [['平聲', 'p'], ['', 'b']]],`
「改寫韻母」寫成`韻母 = { iou: 'iu', uei: 'ui', 如此類推 }[韻母] || 韻母;`
之類。
