### ISSUE TITLE
老國音

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-examples#59]
老國音雖只有十年歷史，但我覺得也值得研究，應該加入。拼音方案我覺得應該有國際音標和注音符號，其他方案讓其他人決定。
攷：
https://zh.wikiversity.org/zh-hant/%E8%80%81%E5%9C%8B%E9%9F%B3%E8%88%87%E5%BB%A3%E9%9F%BB%E5%B0%8D%E6%AF%94
https://github.com/lyczwy/Old-National-Pronunciation
https://github.com/jacob-us/lau_guoq_in

**Comment by ayaka14732** [comment]
歓迎，可以 pr

**Comment by syimyuzya** [comment]
已有 PR #60
