### ISSUE TITLE
戈三韻眞的是輕脣韻嗎？

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-examples#67]
脣音就只有「縛」字。

**Comment by syimyuzya** [comment]
切韻音系沒有「輕脣音」，不過這個「縛」是「脣音三等C類」問題不大。
而且「脣音C類」與韻圖等音系的「輕脣」確實是可以認為完全對應的。「輕脣十韻」沒有列歌（戈）韻，是因為以前往往認為它無字，所以不作討論而已。

如果是推導近現代音系，考慮到這個「並三C歌去」的「縛」在近現代可能幾乎沒有傳承的音，必要的話可以適當外推。

**Comment by syimyuzya** [comment]
（由於不是 tshet-uinh-examples 的關聯話題，本 issue 將關閉）【但這問題本身是個好問題！考證《廣韻》各小韻是個正在進行中的前沿工作，部分工作成果可以在 [nk2028/tshet-uinh-data](https://github.com/nk2028/tshet-uinh-data) 中看到
