### ISSUE TITLE
可否加入這種人造方言

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-examples#68]
記得之前有人問，如果有種人造方言「有吳語聲母、官話元音和粵語韻尾，會否很像中古漢語？」這樣的問題。
好想聽聽，但我不懂吳語，有沒有人會造？

**Comment by ayaka14732** [comment]
你可以把三個方案合起來

**Comment by 307587** [comment]
欸不對，普通話入聲韻腹不承陽，有韻腹更存古的方言嗎？
