### ISSUE TITLE
推導後世韻母改以「攝、等」爲條件

### ISSUE THREAD

**Issue by untunt** [nk2028/tshet-uinh-examples#73]
TshetUinh.js v0.15 更正了「攝」（元韻歸山攝）並且加入了「韻圖等」，以「攝」和 `音韻地位.韻圖等` 爲條件推導後世韻母不僅使書寫更簡明、更便於維護，而且在語義上更正確，因爲對後世音系來說，多數韻母之間的區別條件是韻圖音系的「攝、等」，而不是切韻音系的「韻、等」，逐個枚舉切韻韻目往往是多餘的

例如普通話推導方案：

https://github.com/nk2028/tshet-uinh-examples/blob/159d3ae830362628cde56addbc52b28b18c40cfa/putonghua.js#L106-L110

可以改爲：

``` javascript
  ['山攝', [
    ['一二等', [['合口', 'uan'], ['二等 牙喉音', 'ian'], ['', 'an']]],
    ['三四等', [['合口', 'üan'], ['', 'ian']]],
  ]],
```

原則上「等」也應該用 `音韻地位.韻圖等`，不過對於使用「切韻等」還是「韻圖等」在方案中不產生區別的情況，不妨直接從簡使用「切韻等」。上面普通話推導方案的片段就是例子：莊組切韻三等應是韻圖二等，無 i 介音，但是方案最終會將 zh 組後的 i 介音刪去，所以這裏用「切韻等」還是「韻圖等」最終不產生區別

對於方言中超韻圖音系的部分，即區分「重韻」，才以「韻」來判斷。例如廣州話部分區分蟹攝一等重韻：

https://github.com/nk2028/tshet-uinh-examples/blob/159d3ae830362628cde56addbc52b28b18c40cfa/gwongzau.js#L82-L86

---

目前需要修改的方案：

- 推導普通話 `putonghua.js`
- 推導廣州話 `gwongzau.js` 的部分攝
- 綾香思考音系 `ayaka_v8.js`
- 合入後的 #60 

應保持修改前後結果一致（除非改前的存在錯誤）

**Comment by syimyuzya** [comment]
好欸～

之前曾經調整過一部分，現在看來確實可以全都調整了。

**Comment by graphemecluster** [comment]
例子是指 https://github.com/nk2028/tshet-uinh-examples/blob/159d3ae830362628cde56addbc52b28b18c40cfa/putonghua.js#L107-L110 嗎

**Comment by graphemecluster** [comment]
之前綾香還曾經寫過這樣的 review
https://github.com/nk2028/tshet-uinh-examples/pull/37#pullrequestreview-964165845

**Comment by untunt** [comment]
啊，我引錯段落了，現在改了

綾香那裏的 review 現在看來是不合理的。我想到了一個更好的表述：對於能從切韻音系推出的方言，其多數韻母也能從韻圖音系推出（即，切韻音系的後代大多都經歷過類似韻圖音系的狀態），那麼在推導這部分韻母時，直接以韻圖音系爲起點即可。以更早的切韻音系作爲起點來推導，不僅多此一舉，而且語義上不夠確切

**Comment by ayaka14732** [comment]
> 對於能從切韻音系推出的方言，其多數韻母也能從韻圖音系推出

我要想一想這句話

**Comment by ayaka14732** [comment]
應該確實是這樣，因為使用韻圖術語是方言學的慣用寫法，所以如果推導方言確實應該這樣使用

![](https://github.com/user-attachments/assets/8a78f7c6-de4d-4b70-a9d0-8bd345291fbd)

**Comment by ayaka14732** [comment]
（才發現這個是強行表格，實際上只是為了分成三欄而已 😂）

**Comment by untunt** [comment]
> 使用韻圖術語是方言學的慣用寫法，所以如果推導方言確實應該這樣使用

這個認識不太好……韻圖音系的音韻地位描述和切韻音系的音韻地位描述都屬於音韻學，前者並不和「方言學」綁定。「方言研究慣用」也不能作爲我們「應該這樣使用」的理由

方言研究用韻圖描述更多，自然是因爲它比切韻描述更好用。當然，以前學界沒有認識到韻圖音系 ≠ 切韻音系，不知道從韻圖音系推方言比從切韻音系推更確切，只把韻圖描述當作一種更好用的中古音描述。現在我們認識到了韻圖音系 ≠ 切韻音系，並且對兩個音系都有了深入了解，就很容易判斷出來從韻圖音系推在多數時候是更確切的（即，符合歷史實際），那麼我們就更可以放心大膽地用韻圖音系推了。「慣用」和「好用」都不是決定性的理由，「確切」才是

**Comment by untunt** [comment]
注：通常來說，官話方言可完全從韻圖音系推出。非官話方言中，晚於切韻音系而早於韻圖音系的成分通常是區分一等重韻和區分切韻三四等。區分一等重韻即分咍泰、分覃談，大多只能在銳音聲母後分

**Comment by ayaka14732** [comment]
重韻在韻圖音系中發音必然相同嗎？會不會有語音相近的情況？

**Comment by untunt** [comment]
必然相同。韻圖音系（以中唐慧琳反切爲具體字音的代表）一個音節的發音由 {三十六字母、開合、韻圖等、攝、四聲} 五元組決定，兩個音節只要五元組相同，發音就相同。因此，同等的重韻都合併了，僅東三鍾除外：東三鍾在韻圖音系中被視爲開合之別，東三是開口，鍾是合口，在脣音以外的聲母後區分

**Comment by untunt** [comment]
今天很巧又遇到一個好例子。有人問：

> 为什么很多地方“色”“式”不同韵，他们切韵不都是“职”吗

這個問題最簡便的（並且是正確的）解答就是兩個字分屬韻圖二三等，所以演變跟曾梗攝其他聲母的二三等一樣
