### ISSUE TITLE
建議將方案以質量分類：質量未達標的方案自成一類

### ISSUE THREAD

**Issue by 307587** [nk2028/tshet-uinh-examples#74]
>【因為本專案是「examples」，想要進入（v0.15+ 的）examples 的話，恕我們要在代表性和質量上要求比一般方案高一些

我建議，「S級未滿」但又是v0.15+格式（韻母名？`when`語法？）的方案自成一類，叫「實驗中的方案」之類，如老國音、南京音那些；「examples」升格叫「模範方案」。

**Comment by ayaka14732** [comment]
現在就是由 PR 審核的方式，好的才合併
